# project informations for Bukkit in order to register our plugin with all it components
# ${-} are variables from Maven (pom.xml) which will be replaced after the build
name: ${project.parent.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.${project.name}

# meta informations for plugin managers
authors: [games647, 'https://github.com/games647/CommandForward/graphs/contributors']
description: |
    ${project.description}
website: ${project.url}
dev-url: ${project.url}

# This plugin don't have to be transformed for compatibility with Minecraft >= 1.13
api-version: 1.13

commands:
    forward:
        description: 'Forward a command to the bungee proxy'
        usage: /<command> <player-name or 'console'> <bungee_command> [arg]
        permission: ${project.artifactId}.command.forward
permissions:
    ${project.artifactId}.command.forward.*:
        description: 'Allow to use all features of forward command'
        children:
            ${project.artifactId}.command.forward: true
            ${project.artifactId}.command.forward.console: true
            ${project.artifactId}.command.forward.other: true
    ${project.artifactId}.command.forward:
        description: 'Allow to use base forward command'
    ${project.artifactId}.command.forward.console:
        description: 'Allow to use console in forward command'
    ${project.artifactId}.command.forward.other:
        description: 'Allow to use another player than ourself in forward command'
